### PR TITLE
fix: mouse not working in terminal

### LINKED ISSUE #72: Mouse is not re-enabled when entering buffer with buftype terminal
**Describe the bug**
`hardtime.nvim` does not toggled off when entering buffer with buftype terminal, such as entering `:term`.

**Config options**
None.

**To Reproduce**
1. Open Neovim and have `hardtime.nvim` enabled.
2. Open `buftype=terminal` buffer, such as `:term`.
3. Trying to exit out of Terminal mode by clicking mouse.
4. Stuck.

**Expected behavior**
`hardtime.nvim` are toggled off when entering buffer with buftype terminal.

**Screenshots**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by hankertrix**
Also updated the deprecated function `nvim_buf_get_option` to `nvim_buf_get_option_value`.

Fixes #72

### CODE REVIEW

**Comment by hankertrix** [comment]
Any feedback on this?

This fixes using the mouse to exit terminal mode and ensures the terminal window behaves normally.

Before this fix, it was impossible to view the full output generated by a command if it was very long.

**Comment by m4xshen** [comment]
@hankertrix thanks for the PR, I just tried it out and an error happens:

```
E5108: Error executing lua: ...ocal/share/nvim/lazy/hardtime.nvim/lua/hardtime/init.lua:43: attempt to call field 'nvim_buf_get_option_value' (a nil value)     
stack traceback:                                                                                                                                                
        ...ocal/share/nvim/lazy/hardtime.nvim/lua/hardtime/init.lua:43: in function 'should_disable'                                                            
        ...ocal/share/nvim/lazy/hardtime.nvim/lua/hardtime/init.lua:49: in function <...ocal/share/nvim/lazy/hardtime.nvim/lua/hardtime/init.lua:48>
```

My version:

```
NVIM v0.10.2                                                                                                                                                    
Build type: Release                                                                                                                                             
LuaJIT 2.1.1732813678  
```

**Comment by hankertrix** [comment]
Okay, I fixed the issue.

File: lua/hardtime/init.lua [hunk 1]
```diff
@@ -187,12 +187,36 @@ function M.setup(user_config)
...
+         group = hardtime_group,
          callback = function()
             reset_timer()
          end,
       })
+
+      vim.api.nvim_create_autocmd("TermEnter", {
+         group = hardtime_group,
+         callback = function()
+            if config.disable_mouse then
```
Comment (m4xshen) [inline lua/hardtime/init.lua:202]: We should ignore the `disable_mouse` here. When Hardtime is in terminal, it should be fully disabled, which means mouse is allowed. In this way it fixes #72.

File: lua/hardtime/init.lua [hunk 2]
```diff
@@ -187,12 +187,36 @@ function M.setup(user_config)
...
+         callback = function()
+            if
+               config.disable_mouse
+               and vim.api.nvim_get_option_value("buftype", { buf = 0 })
+                  ~= "terminal"
+            then
+               vim.opt.mouse = ""
+            end
+         end,
+      })
```
Comment (m4xshen) [inline lua/hardtime/init.lua:219]: Instead of only handle the case for terminal. We should also handle it for other filetypes in `disabled_filetypes`.

**Review by m4xshen — CHANGES_REQUESTED** [review]

**Comment by hankertrix** [comment]
Okay I have updated the code.

File: lua/hardtime/init.lua (hunk 2 above)
Comment (m4xshen) [reply lua/hardtime/init.lua]: @hankertrix seems that this is not resolved yet

Comment (hankertrix) [reply lua/hardtime/init.lua]: Uhm, which part isn’t resolved yet?

The function now calls `should_disable`, which covers all the disabled file types.

It still needs to check whether disabling the mouse is wanted before it disables the mouse when leaving terminal mode. Otherwise people who have configured to not disable the mouse would have their mouse disabled.

Comment (m4xshen) [reply lua/hardtime/init.lua]: > Instead of only handle the case for terminal. We should also handle it for other filetypes in `disabled_filetypes`.

This one

**Comment by hankertrix** [comment]
I believe this should be resolved with the call to `should_disable`, which includes the `disabled_filetypes`.Let me know if I’m missing something.On 20 Dec 2024, at 3:47 PM, Max Shen ***@***.***> wrote:﻿
@m4xshen commented on this pull request.



In lua/hardtime/init.lua:
> +
+      vim.api.nvim_create_autocmd("TermEnter", {
+         group = hardtime_group,
+         callback = function()
+            if config.disable_mouse then
+               vim.opt.mouse = "nvi"
+            end
+         end,
+      })
+
+      vim.api.nvim_create_autocmd("TermLeave", {
+         group = hardtime_group,
+         callback = function()
+            if
+               config.disable_mouse
+               and vim.api.nvim_get_option_value("buftype", { buf = 0 })
+                  ~= "terminal"
+            then
+               vim.opt.mouse = ""
+            end
+         end,
+      })


Instead of only handle the case for terminal. We should also handle it for other filetypes in disabled_filetypes.

This one

**Comment by m4xshen** [comment]
> I believe this should be resolved with the call to `should_disable`, which includes the `disabled_filetypes`. Let me know if I’m missing something.

Yeah, but `TermEnter` only occurs when the user enters insert mode in terminal. Therefore, `should_disable` is not called when the user enters a file type such as `help`.

**Comment by hankertrix** [comment]
Ah okay, I get what you want now.

**Comment by hankertrix** [comment]
I made the changes to the code so that the mouse is always enabled for disabled file types.

**Comment by m4xshen** [comment]
Thanks a lot for the PR!

**Comment by hankertrix** [comment]
You’re welcome!

Thanks for merging!
